export const cardContentList = [
  'If you can speak another language, take 2 sips',
  'Take 2 sips if you are in either the medical, law or engineering field',
  'Take 2 sips if you had rice in the past 24 hours',
  'Drink if you are 165cm or shorter',
  'Every lady take 2 sips',
  'Every man take 2 sips',
  "If you've every owned Crocs, drink.",
  'Whoever has a tattoo must drink, then show everyone their dope ink.',
  "Drink if you won a superaltive in high school. What'd ya win?",
  "If you've ever owned Crocs, drink.",
  'Which player is most addicted to social media? The person with the most votes must go put their phone in the kitchen. And take a drink.',
  'Which player has had sex in the most exotic location? The person with the most votes drinks.',
  'In a fight between the youngest and the oldest players, who would win? The person with the most votes gives out two drinks.',
  'Which player is the horniest? The person with the most votes drinks',
  "Do you sleep on the left or right side of your bed? Everyone votes, losing team drinks. If you don't sleep on a specific side, drink twice",
  'Drink if your Instagram bio includes the city or state you live in. By the way, nobody cares.',
  'Which player would be the best in bed? The person with the most votes drinks.',
  'Challenge another player to a thumb war. The loser drinks.',
  "Drink if you've run from the polics",
  'Take a drink if your mom still makes your doctor appointments. And then grow the fuck up.',
  "Drink if you've participated in a Thanksgiving 5K.",
  'Which player can come up with the best idea for an app off the top of their head? The person with the most votes gives out three drinks.',
  'Which player has the best smile? The person with the most votes drinks.',
  'Which player can guess the time most accurately? (No peeking!) The winner gives out a drink.',
  'Which player has the hottest dad? The person with the most votes drinks.',
  "Drink if you've ever been arrested.",
  'The two players who have known each other the longest take a drink together.',
  "Take a drink if you're a pet owner. Cheers to your fur baby.",
  'The playr with the largest show size takes a drink. Also, congrats on the huge dick, bro.',
  "Drink if you haven't eaten a vegetable today",
  'Drink if you have roomates - one drink for each one you have',
  'Drink if you had a swimming pool growing up, you lucky bastard.',
  'Which player can do the best impression of me? That person gives out a drink.',
  "Every player who's a Scorpio takes a drink. Your parents probably fucked on Valentine's Day. Ever think about that?",
  'If you had an inhaler growing up, inhale your beverage.',
  "Drink if you've ever had mono.",
  'Drink if you have to go to work in the morning.',
  `Choose a person to spell "guarantee". If they can't, send a drink their way.`,
  `take a drink if you've ever seen "The Human Centipede". Also, explain yourself.`,
  'Those who have fooled around in a movie theater, drink twice. Then get a fucking room.',
  'Drink if you own a water bottle that has become like a child to you.',
  'Drink if your family has a Costco membership',
  'All players lay their phones on the table. Wait for the first person to receive a push notification. That person drinks.',
  'Every player over six feet tall takes a drink for each inch over six feet.',
  'The person who had coffee most recently, have a drink right now.',
  'Quick: last person to slep their own ass drinks.',
  'Players who currently have ChapStick with them, put those moisturised lips on your drink and take a smooth sip.',
  "If you've ever flown first class, put your pink up, and drink to being boujie.",
  'On the count of three, players point at the person most likely to order chicken fingers at a fancy restaurant. Whoever has the most fingers pointed at them drinks.',
  'Which player most needs to be checked into anger management? The person witht he most votes drinks to CHILL THE FUCK OUT.',
  'Drink if you actually purchased a fidget spinner in 2017.',
  'All players who have AirPods must drink. And consider sending a $1 Venmo to all the other peasants in the room.',
  "Drink if you've never watched Game of Thrones.",
  "If you're not following Beyonce on Instagram, drink. How dare you?",
  'If you have any tattoos take a drink.',
  "If you've ever had blonde hair, drink.",
  "Everybody guess my phone's battery precentage. The person who is closest picks someone else to drink.",
  'Sleep talkers, take a drink; sleep walkers, take 2.',
  "All players who have stickers on their laptops must drink. Everyone say what you were for Halloween last year. Everyone votes on the best costume, and that person chooses someone to drink. If you didn't dress up, drink twice.",
  'All players with an Uber rating at or below 4.5 stars must drinks.',
  'The player with the oldest phone must drink.',
  'If I can see your ankles right now, take a drink.',
  "Whoever is in the picture on their phone's background drinks",
  'Every blondie takes a drink. Cheers to being the funniest!',
  'If you took karate as a kid, show us your best karate chop, then take a drink',
  "Drink if you're in a serious relationship - one drink for each year you've been dating your significant other.",
  "If you've ever had a Tumblr, drink up.",
  'Drink if you ever took piano lessons as a kid.',
  'Drink if you enjoy the smell of gasoline.',
  "Every player who's sitting cross-legged takes two drinks.",
  'Count to three, then everyone points at the player they weant to take a drink. Drink as many times as you were pointed at.',
  'Which player needs a hug the most? The person with the most votes gets a hug. No drinks, just hugs.',
  'QUICK: everyone touch your head with both hands! The last person to do so drinks.',
  'The host of the party chooses a player to drink twice.',
  'Everyone drinks once for every Apple product they own.',
  "Take a drink if you've ever been to Coachella. And then shut the fuck up about it for the rest of the night.",
  'Which player would make the best motivational speaker? Vote, and then that person drinks and gives us a little life wisdom.',
  'Drink if you hvae multiple alarms set on your phone that are only minutes apart.',
  'Everypne must take a sip of their drink without their hands.',
  'If this is your first time playing Buzzed, take 2 drinks.',
  'The host of the part nominates a player to give a heartfelt speech about what this friendship means to them. Then they both take a drink.',
  'Who has had the most regrettable hairstyle? That person gives a drink to the player of their choice.',
  'Take a drink if you currently have a condom in your purse or wallet.',
  'QUICK: take a picture of me with the flash on. The first player to do so decides who must take a drink.',
  "Every player with dyed hair takes a drink. You ain't foolin' nobody.",
  "If you've been on a road trip longer than five hours, drink like you don't have to stop for a bathroom break.",
  'The player reading this card must hum a song. First player to guess the song correctly gives out a drink.',
  'Everyone who would rather be at home watching "Planet Earth" high right now instead of being at this party takes a drink.',
  'Drink if you believe in ghosts.',
  'Which player would be most likely to die in a scary movie? The person with the most votes drinks.',
  'Which player is most likely to wear the same pair of underwear for a week straight? The person with the most votes drinks.',
  'Every player takes a drink for each year they had braces.',
  'Do your best celebreity impression. The first person to correctly guess your identity chooses someone else to drink.',
  "Take a drink if you've ever given or received road head. Don't lie, you kink bastards.",
  'Drink if you read the news today. You need that drink.',
  'Which player would be the leader of a prison gang? That person gives out a drink.',
  "If you've seen every Harry Potter movie, drink. No muggles allowed.",
  'The player who has broken the most bones takes one drink for each break.',
  'And the show must go on. Theater kids, the spotlight is on you. Drink up.',
  "If your name is John, Chris, Michael, Amy, Jessica or Emma, drink on behalf of your parents' lack of originality.",
  'Players wearing a watch take a drink. We have cell phones for that now, dummies.',
  'Blondies, cheers to being the funniest.',
  'Drink if you do your own takes. But also, congrats on being a real adult.',
  'Everyone who has drunk texted their ex in the last month must drink.',
  "Drink if you've ever invested in Bitcoin (if you can afford one more sip).",
  "Drink if you've ever been fired.",
  'If you have more than 3 keys on your key ring. drink up.',
  "Take a drink if you don't know how old your mum is.",
  "Drink if you're on your period.",
  'Give out a drink for each ex-girlfriend/boyfriend you have.',
  'All players who have an Alexa or Google Home must drink.',
  'All players check what colour underwear they have on. Whoever is wearing the same colour, drink together.',
  'The payer reading this card gets toi choose an item in the room that another player must hold. That person must continue to hold the item until they finish their drink.',
  "Every player who knows how to solve a Rubik's Cube gives out two drinks.",
  "Drink if you've secretly thrown up at a part and then acted like nothing happened.",
  'Anyone who has milked a cow, drink and tell us how it made you feel.',
  'Everyone who brought a vape tonight takes a drink.',
  "Drink if you've ever gone to class high.",
  'Which player has the fullest drink right now? Take three drinks. Time to catch up, buddy.',
  "All players who are using someone else's Netflix account must drink.",
  'All players with an Android must grip it n sip it.',
  'Everyone who is younger than you takes a drink.',
  'All players who wished you a happy birthday this past year take a drink.',
  'Whoever had to drink last round drinks again, bitch.',
  "The player who smoked a cigarette most recently takes a drink (vapes don't count).",
  'Reverse the rotation of the game. Everyone drinks.',
  'Players who are vegetarian, drink.',
  'On the count of 3, everyone say their favourite sex position. Whoever has the same answer, cheers and drink.',
  'All players take turns complimenting you. The player who gives the best compliment gives out a drink.',
  'Which player can make the best horse noise? The person with the most votes gets to give out a drink.',
  "Drink if you've ever lost over $300 in a casino. Sorry for your loss.",
  'The player whose drink is most full must drink 3 times. Time to catch up, buddy.',
  'Male players take a drink for each female player in the room.',
  "Drink if you're friends with you mum on Facebook.",
  "All players who are looking at their phone right now must take 4 sips. 2 sips if you're touching it with your hand.",
  'Everyone who knows how to roll a joint takes a drink.',
  'Everyone who has seen a dick on Chatroulette must drink.',
  'Drink if this is your third day drinking in a row.',
  'Go around the circle saying the alphabet backward. The person who fucks up first drinks.',
  "Players wearing all black: this isn't a funeral. Drink up.",
  'Everyone who has ever done Molly at a music festival drink.',
  "Drink if you've ever been to Alice Springs.",
  "Everyone build up a drumroll until I decide who I'd like to drink.",
  "The player who's DJing right now takes a lil sip. We appreciate the fuck outta you.",
  'The player who broguht this game to the party gives out three drinks.',
  'Toy Story<sup>TM</sup> or The Incredibles<sup>TM</sup>? Everyone votes on which one they prefer. Losing team drinks.',
  'If you currently volunteer somewhere, take a break from saving the world and drink.',
  'Choose someone to play you in rock, paper, scissors. Remaining players bet on who will win. Losers drink together in shame.',
  'All players must reveal their screen name or teenage email. The person with the mst embarrassing one must drink.',
  'Which would you rather give up, oral sex or cheese? Everyone votes; the losing team drinks.',
  "Take a drink if you own a pair of Vans<sup>R</sup> and don't skate. Cheers, posers.",
  "Every player who has dimples must drink up, you fuckin' cuties.",
  "The youngest player takes a drink. Don't blame us; blame your parents for not fucking sooner.",
  'The player with the longest middle finger takes a drink.',
  "Drink if you've made a woman cum before.",
  `Vote on how to properly say "caramel". Losing team drinks.`,
  'Which player is most likely to get high before a job interview? The person with the most votes drinks.',
  'Take turns naming fast-food chains. The first person to fuck up drinks.',
  'The tallest player and the shortest player hug, then take a drink together.',
  "Everyone who isn't following me on Instagram<sup>(R)</sup>, throw me a follow to help my ratio. Then drink. If I don't have an account, I must drink.",
  'Every player with an outie belly button takes a drink.',
  'If you think pineapple belongs on pizza, go fuck yours--- ... I mean, drink.',
  'The player reading this card must switch an article of clothing with anothe rplayer, then both players take a drink.',
  'All players who have dated another player must take a drink.',
  'If you do yoga or pilates, you have plenty of headspace for another drink.',
  'Drink if you voted in the last election. Cheers to democracy!',
  'Mexican or Chinese food? Everyone votes and the losing team drinks twice.',
  'If you like cottage cheese, take a drink.',
  'Take a drink if you own a University jumper.',
  'Ketchup or mustard on a hot dog? Losing team drinks. If you put both, also drink.',
  'The next player you make eye contact with must take a drink.',
  'Female players take a drink for each male player in the room.',
  'Any player with a crached phone screen must drink.',
  'Drink if you have a kid.',
  'Drink if you only speak English.',
  'Go around in a circle and name different kinds of sushi rolls. First one to fuck up drinks.',
  'Which player has the funniest losing-their-virginity story? The person with the most votes gets a pass; everyone else drinks.',
  `Drink if you ever studied abroad in Europe and "it totally changed your life.`,
  // Altered
  'Drink if you took the highest level maths in high school, nerd.',
  "Take a drink if you've every Avengers movie. You fantastic geek.",
  "Everyone votes on the person who looks the most decent in their ID pic compared to real life. You can't vote for yourself. The winner picks someone else to drink.",
  `Put on the chorus for Eminem's "Lose Yourself" and sing along. Everyone who doesn't know the lyrics must take a drink`,
  'Players who can play an instrument must reveal what they can play and then take a drink.',
  'Drink if you represented your high school competitively in a sport.',

  // Additional

  "Each person who isn't wearing any underwear gives 3 sips to someone. Cheers to freedom!",
  'Drink if you have at least one pet.'
];

export const asianCardContentList = [
  'If your parents had/currently have a small business, take 3 sips',
  'Vote: Ramen or Pho? Which is better? Losing team takes 3 sips',
  'If you majored in Computer Science, take 3 sips',
  'Storytime: Go around the table and share the time you thought your parents were literally going to kill you. Skip = 2 sips. Choose the best story. Winner gives out 3 sips.',
  'Categories: Foods we eat, but the rest of the world would consider disgusting. Loser takes 3 sips.',
  "For the guys: If you've ever been friendzones by the cute white girl, take 3 sips.",
  'Most likely to: On 3, everyone point at the person who is most likely to be an ABG. Winner takes 4 sips.',
  'If you have airpods, take 77 sips. JK take 3 sips.',
  'If you can speak korean, drink 2 sips',
  'If you can speak Mandarin chinese, drinks 2 sips',
  'If you can speak any dialect of chinese apart from Mandarin, take 2 sips',
  "If you've ever calculated the lowest grade you need to get to keep an A, take 7 sips.",
  'If you were pre-med at one point, take 4 sips/=.',
  "If you've never failed a test, take 2 sips.",
  "Most likely: On 3, every point at the person who is most 'Asian', winner gives 5 sips.If you have a rice cooker that plays a tune when it's finished, take 2 sips",
  "If you're friend who suggested this game, take 10 sips & give 10 sips.",
  'If John Cena speaks better Mandarin than you do, take 2 sips.',
  'If you name is Alex, Jennifer (Jenny), Daniel or Eunice, take 2 sips.',
  "If you love KPop but aren't korean, take 3 sips.",
  `If you're over 175cm, take 5 sips.`,
  'Vote: KPop/Dramas vs Anime? Which is better? Losing team takes 2 sips.',
  'Categories: Asian candies. Loser takes 2 sips.',
  "If you've ever texted xD, take 5 sips.",
  'AZN Flush Check: Whoever has the most glorious Asian flush, go get some water please. 4 sips of H2O.',
  'If you have Wechat or Kakao Talk installed on your phone, give 2 sips.',
  "If you've ever done the blindfolded Boba Lid Challenge, take 2 sips.",
  "If there's a drawer somewhere in your house full of plastic bags, take 4 sips.",
  "If you've ever been mistaken for another Asian, take 3 sips.",
  'If you still get carded because of how young you look, take 2 sips.',
  'AZN Flush Check: Whoever has the most goregeous Asian flush gets to pick one person to share tinder profile with the group. If they refuse, 4 sips.',
  'If your cousin is doing better than you are, take 2 sips.',
  'If you grew up with a plastic cover on your tv remote, take 3 sips.',
  'If your parents are low-key racist, take 3 sips. High-key? 5 sips.',
  "If you can't speak your native language, take 5 sips.",
  'Did you take the highest level maths in hgh school? Take 2 sips.',
  'The person with the chinkiest eyes drinks 4 sips.',
  'If you studied engineering, law or medicine, take 3 sips.',
  "If there's anyone who's not Asian and playing with you right now, that person takes 6 sips.",
  'Categories: Asian dishes, loser takes 3 sips.',
  "Categories: Things Asians are supposedly good at because we're Asian. Loser takes 2 sips.",
  'Categories: Wok puns. Loser takes 3 sips.',
  'Most Likely to: On the count of three, everyone point at the person most likely to pay for bubble tea instead of rent. Winner takes 4 sips',
  "If your mom always reminds you that you're fat when you've gained literally 0.1 kg, take 2 sips.",
  'Most likely to: On 3, everyone point to the person most likely to blackout after one shot of alcohol. Winner drinks a glass of water.',
  `If you ever unironically said "Boba is lyfe", give 3 sips.`,
  'If your last name is Nguyen, Lee or Wong, take 3 sips.',
  'Categories: Things Asian parents would never say. Loser takes 3 sips.',
  'If your name is Kevin, Jessica, Michael or Katherine, take 4 sips. If no one has the name, I take 7 sips.',
  "If you don't use chopsticks the proper way, take 5 sips.",
  'Categories: Asian liquor. Loser takes 3 sips.',
  `If you're under 160cm but insist on dating someone over 180cm, take 5 sips.`,
  `If you cried while watching the pixar's "BAO", take 3 sips.`,
  'Pick a person in the room. On 3, both of you call out the best Asian noodles. If you have different answers, take 3 sips.',
  'Storytime: Go Around and share the time you first found out how disrespectful white kids are to their parents. Choose the best story. Winner gives 4 sips.',
  'Most likely to: On 3, everyone point to the person most likely to take a Snapchat or Instagram photo of their food before eating. Winner takes 3 sips.',
  "If you've dated a white girl/guy, take 4 sips.",
  "If the teacher couldn't pronounce your name right on the first day of school, take 3 sips.",
  'Categories: Pokemon. Loser takes 3 sips.',
  'If you own real estate in the friend zone, take 1 sip.',
  'Most likely to: On 3, everyone point at the person most likely to spend the most time on their make-up every morning. Winner takes 3 sips.',
  "If you've ever been spanked by slippers, broom handles or bamboo sticks, take 5 sips.",
  'Most likely to: On 3, everyone point at the person who is most likely to know an entire Kpop dance. Winner takes 5 sips.',
  'Go around and say when the last time you had rice was. Whoever ate it most recently gives 3 sips.',
  "If you're in Subtle Asian Traits, take 2 sips.",
  'Most likely to: On 3, everyone point to the person most likely to go back and live in the motherland. Winner takes 2 sips.',
  'If you posted a Facebook status about how happy you were to watch Crazy Rich Asians, take 3 sips.',
  "If you're playing this as part of an Asian American club or sorority, take 4 sips. If not, and you're playing this at home with your other alcoholic friends, take 2 sips.",
  "Storytime: Go around the table and share the fattest lie you've ever told your parents. Skip = 3 sips. Choose the best story. Winner gives 3 sips.",
  'Most likely to: On 3, everyone point at the person who you think go spanked the most. Loser takes 6 sips.',
  "If you've never dated as Asian before, take 3 sips.",
  'AZN Flush check: Whoever has the most glorious Asian flush has to kiss the person on their left. If not, take 4 sips.',
  'If the first time you ever drank alcohol was in college, take 2 sips.',
  "Categories: Household items that you've been spanked with. Loser takes 2 sips.",
  'AZN Flush Check: Whoever has the most glorious Asian flush has to take off one item of clothing. If not, take 3 sips.',
  "Most likely to: On 3, everyone point at the person who swears she's a gamer. Winner takes 4 sips.",
  'Categories: Asian stereotypes. Loser takes 2 sips.',
  "If you're playing this game without alcohol right now, take 69 sips. Not a typo.",
  'If you spent more time in tutoring than getting laid in high school, take 3 sips.',
  'Categories: Asian countries. Loser takes 3 sips.',
  'If your dishwasher is more like a drying rack, take 4 sips.',
  'AZN Flush check: No Asian flush? take 6 sips.',
  'If you have a traditionally Asian first name, take 2 sips.',
  'If you ever fantasised about being with Big Bang of BTS, drink 4 sips.',
  'Categories: Pho puns. Loser takes 4 sips.',
  "If you've ever been to Japan or Korea, take 4 sips.",
  'Categories: Animes. Loser takes 3 sips.',
  'Most likely to: On 3, everyone point to the person most likely to use an Asians-only dating app. Winner takes 4 sips.',
  "If you're under 170cm, take 4 sips.",
  'AZN girls: If you truly believe Asian guys have the smallest dicks, take 2 sips.',
  `If you had "azn" in any of your online screen names or emails, take 4 sips`,
  "Most likely to: On 3, everyone point at the person who was the biggest teacher's pet. Winner gives 5 sips.",
  'If you played League of Legends or Dota instead of studying for your Math exam, take 7 sips.',
  'If you know what UwU is, take 3 sips.',
  'If you were in elementary gifted and talented program, take 4 sips.',
  'If your starter Pokemon was Charmander, take 4 sips.',
  'First person to calculate 22 x 37, gets to give out 14 sips. (Answer: 814)',
  'Pick Two: pick people playing. Everyone votes on who they think got the higher ATAR score. Losing team takes 2 sips.',
  'If YuGiOh, Naruto, or Avatar was one of your favourite shows growing up, take 3 sips.',
  "If you've ever fallen in love with rave bae, take 3 sips.",
  'Vategories: Asian Pop Stars, loser takes 3 sips.',
  'If your mum cut your hair and gave you a bowl cut when you were younger, show us the picture or take 4 sips.',
  'AZN Flush Check: Whoever has the worst Asian flush makes a new rule. Get creative.',
  'AZN Flush Check: Whoever has the most glorious Asian flush has to take a selfie and send it to their mum. If not, take 2 sips.',
  'Most likely to: On 3, everyone point at the person who spent more time on their coachella outfit than their college application. Winner takes 4 sips.',
  'Pick Two: Pick two types of Asian cuisine. Everyone votes on which one is better. Losing team takes 3 sips.',
  'If you can speak philipino, take 3 sips'
];
