export const cardContentList = [
  'If you can speak another language, take 2 sips',
  'Take 2 sips if you are in either the medical, law or engineering field',
  'Take 2 sips if you had rice in the past 24 hours',
  'Drink if you are 165cm or shorter',
  'Every lady take 2 sips',
  'Every man take 2 sips',
  "If you've every owned Crocs, drink.",
  'Whoever has a tattoo must drink, then show everyone their dope ink.',
  "Drink if you won a superaltive in high school. What'd ya win?",
  "If you've ever owned Crocs, drink.",
  'Which player is most addicted to social media? The person with the most votes must go put their phone in the kitchen. And take a drink.',
  'Which player has had sex in the most exotic location? The person with the most votes drinks.',
  'In a fight between the youngest and the oldest players, who would win? The person with the most votes gives out two drinks.',
  'Which player is the horniest? The person with the most votes drinks',
  "Do you sleep on the left or right side of your bed? Everyone votes, losing team drinks. If you don't sleep on a specific side, drink twice",
  'Drink if your Instagram bio includes the city or state you live in. By the way, nobody cares.',
  'Which player would be the best in bed? The person with the most votes drinks.',
  'Challenge another player to a thumb war. The loser drinks.',
  "Drink if you've run from the polics",
  'Take a drink if your mom still makes your doctor appointments. And then grow the fuck up.',
  "Drink if you've participated in a Thanksgiving 5K.",
  'Which player can come up with the best idea for an app off the top of their head? The person with the most votes gives out three drinks.',
  'Which player has the best smile? The person with the most votes drinks.',
  'Which player can guess the time most accurately? (No peeking!) The winner gives out a drink.',
  'Which player has the hottest dad? The person with the most votes drinks.',
  "Drink if you've ever been arrested.",
  'The two players who have known each other the longest take a drink together.',
  "Take a drink if you're a pet owner. Cheers to your fur baby.",
  'The playr with the largest show size takes a drink. Also, congrats on the huge dick, bro.',
  "Drink if you haven't eaten a vegetable today",
  'Drink if you have roomates - one drink for each one you have',
  'Drink if you had a swimming pool growing up, you lucky bastard.',
  'Which player can do the best impression of me? That person gives out a drink.',
  "Every player who's a Scorpio takes a drink. Your parents probably fucked on Valentine's Day. Ever think about that?",
  'If you had an inhaler growing up, inhale your beverage.',
  "Drink if you've ever had mono.",
  'Drink if you have to go to work in the morning.',
  `Choose a person to spell "guarantee". If they can't, send a drink their way.`,
  `take a drink if you've ever seen "The Human Centipede". Also, explain yourself.`,
  'Those who have fooled around in a movie theater, drink twice. Then get a fucking room.',
  'Drink if you own a water bottle that has become like a child to you.',
  'Drink if your family has a Costco membership',
  'All players lay their phones on the table. Wait for the first person to receive a push notification. That person drinks.',
  'Every player over six feet tall takes a drink for each inch over six feet.',
  'The person who had coffee most recently, have a drink right now.',
  'Quick: last person to slep their own ass drinks.',
  'Players who currently have ChapStick with them, put those moisturised lips on your drink and take a smooth sip.',
  "If you've ever flown first class, put your pink up, and drink to being boujie.",
  'On the count of three, players point at the person most likely to order chicken fingers at a fancy restaurant. Whoever has the most fingers pointed at them drinks.',
  'Which player most needs to be checked into anger management? The person witht he most votes drinks to CHILL THE FUCK OUT.',
  'Drink if you actually purchased a fidget spinner in 2017.',
  'All players who have AirPods must drink. And consider sending a $1 Venmo to all the other peasants in the room.',
  "Drink if you've never watched Game of Thrones.",
  "If you're not following Beyonce on Instagram, drink. How dare you?",
  'If you have any tattoos take a drink.',
  "If you've ever had blonde hair, drink.",
  "Everybody guess my phone's battery precentage. The person who is closest picks someone else to drink.",
  'Sleep talkers, take a drink; sleep walkers, take 2.',
  "All players who have stickers on their laptops must drink.Everyone say what you were for Halloween last year. Everyone votes on the best costume, and that person chooses someone to drink. If you didn't dress up, drink twice."
];
