import { GameTypesEnum } from '../enums';

export const asianCardContentList = [
  'If your parents had/currently have a small business, take 3 sips',
  'Vote: Ramen or Pho? Which is better? Losing team takes 3 sips',
  'If you majored in Computer Science, take 3 sips',
  'Storytime: Go around the table and share the time you thought your parents were literally going to kill you. Skip = 2 sips. Choose the best story. Winner gives out 3 sips.',
  'Categories: Foods we eat, but the rest of the world would consider disgusting. Loser takes 3 sips.',
  "For the guys: If you've ever been friendzones by the cute white girl, take 3 sips.",
  'Most likely to: On 3, everyone point at the person who is most likely to be an ABG. Winner takes 4 sips.',
  'If you have airpods, take 77 sips. JK take 3 sips.',
  'If you can speak korean, drink 2 sips',
  'If you can speak Mandarin chinese, drinks 2 sips',
  'If you can speak any dialect of chinese apart from Mandarin, take 2 sips',
  "If you've ever calculated the lowest grade you need to get to keep an A, take 7 sips.",
  'If you were pre-med at one point, take 4 sips/=.',
  "If you've never failed a test, take 2 sips.",
  "Most likely: On 3, every point at the person who is most 'Asian', winner gives 5 sips.If you have a rice cooker that plays a tune when it's finished, take 2 sips",
  "If you're friend who suggested this game, take 10 sips & give 10 sips.",
  'If John Cena speaks better Mandarin than you do, take 2 sips.',
  'If you name is Alex, Jennifer (Jenny), Daniel or Eunice, take 2 sips.',
  "If you love KPop but aren't korean, take 3 sips.",
  `If you're over 175cm, take 5 sips.`,
  'Vote: KPop/Dramas vs Anime? Which is better? Losing team takes 2 sips.',
  'Categories: Asian candies. Loser takes 2 sips.',
  "If you've ever texted xD, take 5 sips.",
  'AZN Flush Check: Whoever has the most glorious Asian flush, go get some water please. 4 sips of H2O.',
  'If you have Wechat or Kakao Talk installed on your phone, give 2 sips.',
  "If you've ever done the blindfolded Boba Lid Challenge, take 2 sips.",
  "If there's a drawer somewhere in your house full of plastic bags, take 4 sips.",
  "If you've ever been mistaken for another Asian, take 3 sips.",
  'If you still get carded because of how young you look, take 2 sips.',
  'AZN Flush Check: Whoever has the most goregeous Asian flush gets to pick one person to share tinder profile with the group. If they refuse, 4 sips.',
  'If your cousin is doing better than you are, take 2 sips.',
  'If you grew up with a plastic cover on your tv remote, take 3 sips.',
  'If your parents are low-key racist, take 3 sips. High-key? 5 sips.',
  "If you can't speak your native language, take 5 sips.",
  'Did you take the highest level maths in hgh school? Take 2 sips.',
  'The person with the chinkiest eyes drinks 4 sips.',
  'If you studied engineering, law or medicine, take 3 sips.',
  "If there's anyone who's not Asian and playing with you right now, that person takes 6 sips.",
  'Categories: Asian dishes, loser takes 3 sips.',
  "Categories: Things Asians are supposedly good at because we're Asian. Loser takes 2 sips.",
  'Categories: Wok puns. Loser takes 3 sips.',
  'Most Likely to: On the count of three, everyone point at the person most likely to pay for bubble tea instead of rent. Winner takes 4 sips',
  "If your mom always reminds you that you're fat when you've gained literally 0.1 kg, take 2 sips.",
  'Most likely to: On 3, everyone point to the person most likely to blackout after one shot of alcohol. Winner drinks a glass of water.',
  `If you ever unironically said "Boba is lyfe", give 3 sips.`,
  'If your last name is Nguyen, Lee or Wong, take 3 sips.',
  'Categories: Things Asian parents would never say. Loser takes 3 sips.',
  'If your name is Kevin, Jessica, Michael or Katherine, take 4 sips. If no one has the name, I take 7 sips.',
  "If you don't use chopsticks the proper way, take 5 sips.",
  'Categories: Asian liquor. Loser takes 3 sips.',
  `If you're under 160cm but insist on dating someone over 180cm, take 5 sips.`,
  `If you cried while watching the pixar's "BAO", take 3 sips.`,
  'Pick a person in the room. On 3, both of you call out the best Asian noodles. If you have different answers, take 3 sips.',
  'Storytime: Go Around and share the time you first found out how disrespectful white kids are to their parents. Choose the best story. Winner gives 4 sips.',
  'Most likely to: On 3, everyone point to the person most likely to take a Snapchat or Instagram photo of their food before eating. Winner takes 3 sips.',
  "If you've dated a white girl/guy, take 4 sips.",
  "If the teacher couldn't pronounce your name right on the first day of school, take 3 sips.",
  'Categories: Pokemon. Loser takes 3 sips.',
  'If you own real estate in the friend zone, take 1 sip.',
  'Most likely to: On 3, everyone point at the person most likely to spend the most time on their make-up every morning. Winner takes 3 sips.',
  "If you've ever been spanked by slippers, broom handles or bamboo sticks, take 5 sips.",
  'Most likely to: On 3, everyone point at the person who is most likely to know an entire Kpop dance. Winner takes 5 sips.',
  'Go around and say when the last time you had rice was. Whoever ate it most recently gives 3 sips.',
  "If you're in Subtle Asian Traits, take 2 sips.",
  'Most likely to: On 3, everyone point to the person most likely to go back and live in the motherland. Winner takes 2 sips.',
  'If you posted a Facebook status about how happy you were to watch Crazy Rich Asians, take 3 sips.',
  "If you're playing this as part of an Asian American club or sorority, take 4 sips. If not, and you're playing this at home with your other alcoholic friends, take 2 sips.",
  "Storytime: Go around the table and share the fattest lie you've ever told your parents. Skip = 3 sips. Choose the best story. Winner gives 3 sips.",
  'Most likely to: On 3, everyone point at the person who you think go spanked the most. Loser takes 6 sips.',
  "If you've never dated as Asian before, take 3 sips.",
  'AZN Flush check: Whoever has the most glorious Asian flush has to kiss the person on their left. If not, take 4 sips.',
  'If the first time you ever drank alcohol was in college, take 2 sips.',
  "Categories: Household items that you've been spanked with. Loser takes 2 sips.",
  'AZN Flush Check: Whoever has the most glorious Asian flush has to take off one item of clothing. If not, take 3 sips.',
  "Most likely to: On 3, everyone point at the person who swears she's a gamer. Winner takes 4 sips.",
  'Categories: Asian stereotypes. Loser takes 2 sips.',
  "If you're playing this game without alcohol right now, take 69 sips. Not a typo.",
  'If you spent more time in tutoring than getting laid in high school, take 3 sips.',
  'Categories: Asian countries. Loser takes 3 sips.',
  'If your dishwasher is more like a drying rack, take 4 sips.',
  'AZN Flush check: No Asian flush? take 6 sips.',
  'If you have a traditionally Asian first name, take 2 sips.',
  'If you ever fantasised about being with Big Bang of BTS, drink 4 sips.',
  'Categories: Pho puns. Loser takes 4 sips.',
  "If you've ever been to Japan or Korea, take 4 sips.",
  'Categories: Animes. Loser takes 3 sips.',
  'Most likely to: On 3, everyone point to the person most likely to use an Asians-only dating app. Winner takes 4 sips.',
  "If you're under 170cm, take 4 sips.",
  'AZN girls: If you truly believe Asian guys have the smallest dicks, take 2 sips.',
  `If you had "azn" in any of your online screen names or emails, take 4 sips`,
  "Most likely to: On 3, everyone point at the person who was the biggest teacher's pet. Winner gives 5 sips.",
  'If you played League of Legends or Dota instead of studying for your Math exam, take 7 sips.',
  'If you know what UwU is, take 3 sips.',
  'If you were in elementary gifted and talented program, take 4 sips.',
  'If your starter Pokemon was Charmander, take 4 sips.',
  'First person to calculate 22 x 37, gets to give out 14 sips. (Answer: 814)',
  'Pick Two: pick people playing. Everyone votes on who they think got the higher ATAR score. Losing team takes 2 sips.',
  'If YuGiOh, Naruto, or Avatar was one of your favourite shows growing up, take 3 sips.',
  "If you've ever fallen in love with rave bae, take 3 sips.",
  'Vategories: Asian Pop Stars, loser takes 3 sips.',
  'If your mum cut your hair and gave you a bowl cut when you were younger, show us the picture or take 4 sips.',
  'AZN Flush Check: Whoever has the worst Asian flush makes a new rule. Get creative.',
  'AZN Flush Check: Whoever has the most glorious Asian flush has to take a selfie and send it to their mum. If not, take 2 sips.',
  'Most likely to: On 3, everyone point at the person who spent more time on their coachella outfit than their college application. Winner takes 4 sips.',
  'Pick Two: Pick two types of Asian cuisine. Everyone votes on which one is better. Losing team takes 3 sips.',
  'If you can speak philipino, take 3 sips'
];

const asianDeck = {
  name: 'Asian',
  cards: cardContentList,
  type: GameTypesEnum.asian
};

export default asianDeck;
